export const LOAD_MOVIES = 'LOAD_MOVIES';
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIES_ERROR = 'LOAD_MOVIES_ERROR';
export const SORT_MOVIES_RELEASEDATE = 'SORT_MOVIES_RELEASEDATE';
export const SELECT_MOVIE = 'SELECT_MOVIE';
